[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
solc = '0.8.19'
remappings = [
    '@bancor/=node_modules/@bancor/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@layerzerolabs/=node_modules/@layerzerolabs/',
    '@uniswap/=node_modules/@uniswap/',
    'forge-std/=lib/forge-std/src/'
]
optimizer = true
optimizer_runs = 100_000
